### PR TITLE
Streaming iaga2002

### PR DESCRIPTION
**Pull request by jmfee-usgs**
- updates the iaga2002 output to use a streaming method to minimize memory usage.
- documents and enforces request size limits

NOTE: since output is no longer completely buffered, this may have implications should an error occur during processing.  I've attempted to address this by connecting to the waveserver before any output starts, however, it's possible there are other unexpected issues that may result from this change.

### CODE REVIEW

**Comment by erigler-usgs** [comment]
@jmfee-usgs: 

This looks great! Thanks for taking the extra step of "streaming" the IAGA data. I guess I understand why this is not possible with JSON, and anyone who is more interested in using the JSON data is probably a more savvy programmer, and won't have any trouble writing their own scripts to chunk their data request.

Any reason I should NOT merge this pull request (do you prefer someone from HazDev to do it)?

**Comment by jmfee-usgs** [comment]
@erigler-usgs It appears to work as expected now, and I added a couple more socket handling checks to avoid problems similar to what we saw with obspy in algorithms.  I can deploy to dev, or help you set up a dev environment, if you'd like to test before releasing to production.

**Comment by erigler-usgs** [comment]
@jmfee-usgs: Please deploy to the group's dev server this time. Sometime in the new year I will find and ask you for help setting up my own dev environment, but I'm already struggling to finish up a number of competing projects/manuscripts before the end of the CY, and I should avoid distractions that I might actually find useful or interesting. Thanks!

**Comment by jmfee-usgs** [comment]
A docker image has been pushed `usgs/geomag-edge-ws:streaming-iaga2002`, and the internal instance is running this version.

**Pull request merged**
